import { ArrowLeft, FileText } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { fetchVocReports } from '../services/vocReportService';

function formatDate(value) { return new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)); }

function VocReportHistoryPage() {
  const { workspaceId } = useParams();
  const [reports, setReports] = useState([]);
  const [error, setError] = useState('');

  useEffect(() => { fetchVocReports(workspaceId).then(setReports).catch((requestError) => setError(requestError.response?.data?.message || 'Unable to load report history.')); }, [workspaceId]);

  return <main className="workspace-page"><section className="workspace-container"><Link className="back-link" to={`/workspaces/${workspaceId}/voc-report`}><ArrowLeft size={17} /> Voice of Customer report</Link><header className="page-header"><div><p className="eyebrow">AI Executive Insight</p><h1>Report History</h1><p>Previously generated Voice of Customer reports.</p></div><FileText size={30} className="insights-header-icon" /></header>{error && <p className="form-error" role="alert">{error}</p>}{!error && reports.length === 0 && <section className="empty-state"><FileText size={36} /><h2>No saved reports yet</h2><p>Generate a Voice of Customer report to save it here.</p></section>}{reports.length > 0 && <section className="report-history-list">{reports.map((report) => <Link key={report.id} to={`/workspaces/${workspaceId}/voc-report?reportId=${report.id}`}><FileText size={19} /><span><strong>{formatDate(report.generatedAt)}</strong><small>{report.dateRange.label} · Generated by {report.generatedBy?.fullName || 'Unknown'}</small></span></Link>)}</section>}</section></main>;
}

export default VocReportHistoryPage;
